//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {app} is an VB/C# text editor with the ability to run code and code snippets. It can run a complete code file, or a snippet containing only the inside of a class or the inside of Main().
        ///
        ///The program does not use an interactive console when Console.ReadLine is executed. Instead the text in &quot;Input Data&quot; is used as the input.
        ///
        ///See https://github.com/lwchkg/DotNetEditor for source code and license.
        ///
        ///Credits:
        ///ICSharpCode, for AvalonEdit control (MIT license).
        ///Icons8 (https://icons8.com), for free icons (CC BY-N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aboutbox {
            get {
                return ResourceManager.GetString("aboutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.WriteLine(&quot;Multiplication&quot;)
        ///Console.WriteLine()
        ///
        ///Debug.Print(Mid(&quot;debugging&quot;, 1, 5))
        ///
        ///For i As Integer = 1 To 9
        ///  For j As Integer = 1 To 9
        ///    Console.BackgroundColor = i
        ///    Console.ForegroundColor = j
        ///    Console.Write( _
        ///      (i*j).ToString(&quot;00 &quot;))
        ///  Next
        ///  Console.WriteLine()
        ///Next
        ///
        ///Console.ResetColor()
        ///
        ///Console.WriteLine()
        ///Console.Write(&quot;Enter some text: &quot;)
        ///Dim s As String = Console.ReadLine()
        ///Console.WriteLine(s).
        /// </summary>
        internal static string samplecode {
            get {
                return ResourceManager.GetString("samplecode", resourceCulture);
            }
        }
    }
}
